package com.kkm.fyp.host.exception

enum class ErrorCode {
    ERR_LOGIN_FAILED,
    ERR_SIGNUP_DUPLICATE,
    ERR_ILLEGAL_PASSWORD,
    ERR_INVALID_TOKEN,
    ERR_BAD_GATEWAY,
    ERR_UNKNOWN,
    ERR_USER_NOT_EXIST,
    ERR_ILLEGAL_ARGUMENT,
}